### DISCUSSION TITLE
Recipe for "full" build caching in CI

### DISCUSSION THREAD

**Discussion by BeyondEvil** [dotnet/runtime#108847] [Q&A]
I've tried to find a recipe for a full cache of a dotnet build, but my research hasn't revealed much.

I'm using .NET 8 and Github Actions.

If I run `dotnet build` for my project (ProjectA), it takes me about 2 minutes. If I rerun it, it takes a couple of seconds. So something is obviously being cached.

I've tried to solve this in CI using the `actions/cache` GH action, and I _do_ get a cache hit, but the build still takes the full 2 minutes.

So obviously I'm missing something and/or doing something wrong.

Here's my latest attempt:

```yaml

name: Test on Ubuntu

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  id-token: write

jobs:
  test:
    name: Test on Ubuntu
    runs-on: ubuntu-22.04
    defaults:
      run:
        shell: bash

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Install dotnet
        uses: actions/setup-dotnet@v4
        with:
          global-json-file: global.json

      - name: Restore build artifacts
        id: restore-build
        uses: actions/cache/restore@v4
        with:
          path: |
            ProjectA/build
          key: ${{ runner.os }}-dotnet-build-${{ hashFiles('ProjectA/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-dotnet-build-

      - name: Build
        run: |
          dotnet build --artifacts-path build
        working-directory: ProjectA

      - name: Cache build artifacts
        if: steps.restore-build.outputs.cache-hit != 'true'
        uses: actions/cache/save@v4
        with:
          path: |
            ProjectA/build
          key: ${{ runner.os }}-dotnet-build-${{ hashFiles('ProjectA/packages.lock.json') }}

```

I have more projects in the same repository, some are dependencies to ProjectA.

I've tried using the "built-in" caching that `setup-node` provides, but that seems to only have cached packages.

Now, the above CI workflow works, but it doesn't use the cache, as it takes 2 minutes to run `dotnet build` every time.

```shell
Run actions/cache/restore@v4
Received 192937984 of 230484525 (83.7%), 184.0 MBs/sec
Cache Size: ~220 MB (230484525 B)
/usr/bin/tar -xf /home/runner/work/_temp/51aa203a-8ad4-4a5f-ad82-33c3559cce54/cache.tzst -P -C /home/runner/work/myproject/myproject --use-compress-program unzstd
Received 230484525 of 230484525 (100.0%), 109.7 MBs/sec
Cache restored successfully
Cache restored from key: Linux-dotnet-build-e207bfd1abb820e61911a2fb949eaf5de507bcaf6fb[40](https://github.com/mycompany/myproject/actions/runs/11329397027/job/31504855445#step:4:41)aaf8ac4947036a8ff6e
```

Here's an anonymized version of my .csproj file:

```xml
<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
  </PropertyGroup>
  <ItemGroup>
    <Content Remove="log4net.config" />
  </ItemGroup>
  <ItemGroup>
    <None Include="log4net.config">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="13.0.1" />
    <PackageReference Include="ClosedXML" Version="0.102.3" />
    <PackageReference Include="EasyNetQ" Version="7.8.0" />
    <PackageReference Include="HtmlAgilityPack.NetCore" Version="1.5.0.1" />
    <PackageReference Include="ITfoxtec.Identity.Saml2.MvcCore" Version="4.12.6" />
    <PackageReference Include="log4net" Version="2.0.17" />
    <PackageReference Include="log4net.Ext.Json" Version="2.0.10.1" />
    <PackageReference Include="Magick.NET-Q16-AnyCPU" Version="13.10.0" />
    <PackageReference Include="Microsoft.AspNetCore.DataProtection.EntityFrameworkCore" Version="8.0.8" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Common" Version="8.0.8" />
    <PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" Version="8.0.8" />
    <PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Log4Net.AspNetCore" Version="8.0.0" />
    <PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="8.0.2" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.7.3" />
    <PackageReference Include="Swashbuckle.AspNetCore.Newtonsoft" Version="6.7.3" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.8" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="8.0.8" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="8.0.8" />
    <PackageReference Include="Microsoft.AspNetCore.Owin" Version="8.0.8" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.8" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.8" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Proxies" Version="8.0.8" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.8" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="8.0.4" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\ProjectB\ProjectB.csproj" />
  </ItemGroup>
</Project>
```
