### ISSUE TITLE
build.cmd fails to pick the right MSVC toolset on `1es-windows-2022-open`

### ISSUE THREAD

**Issue by antonfirsov** [dotnet/runtime#100046]
The following simple pipeline fails to build the runtime on `1es-windows-2022-open` outside of docker:

```yaml
trigger: none

pr:
  branches:
    include:
    - "*"

variables:
   - template: ../variables.yml

extends:
  template:  /eng/pipelines/common/templates/pipeline-with-resources.yml
  parameters:
    stages:
    - stage: Build
      jobs:
      - job: windows
        displayName: Test
        timeoutInMinutes: 150
        pool:
          name: $(DncEngPublicBuildPool)
          demands: ImageOverride -equals 1es-windows-2022-open

        steps:
        - checkout: self
          clean: true
          fetchDepth: 5
          lfs: false

        - powershell: |
            & "$(Build.SourcesDirectory)/build.cmd" clr+libs -ci -rc Release -c Release
          name: buildRuntime
          displayName: Build CLR and Libraries
```

For the repro see [this build](https://dev.azure.com/dnceng-public/public/_build/results?buildId=610541&view=logs&j=0bc77094-9fcd-5c38-f6e4-27d2ae131589&t=0eda4080-ac10-5e2b-f8c7-f0b168217e47) from  #100038.

The build fails to pick the right MSVC toolset even though it's present on the machine (see https://github.com/dotnet/runtime/issues/95750#issuecomment-2007204565), and as a result will run into #94723. This is the root cause of #95750 which is blocking HTTP and SSL stress runs on CI.
