### ISSUE TITLE
GetSpecialFolder on macOS returns incorrect folder locations

### ISSUE THREAD

**Issue by MarcoMiltenburg** [dotnet/runtime#100440]
### Description

When calling `Environment.GetSpecialFolder()` on macOS the returned folder is incorrect for a number of special folders. The reason is that for a number of folders the special folder `SpecialFolder.Personal` is used as the home directory of the user combined with a specific value. However the folder returned for `SpecialFolder.Personal` is not the the user's home directory but the user's document directory (`CombineDocumentDirectory(string.Empty)`).

### Reproduction Steps

Get the user's desktop folder by calling:
```
var desktopFolder = Environment.GetFolderPath(Environment.SpecialFolder.Desktop);
```
This returns: `/Users/username/Documents/Desktop`
But should be: `/Users/username/Desktop`

The same is true for others, like: `SpecialFolder.MyMusic`, `SpecialFolder.MyPictures`, `SpecialFolder.MyVideos`, and `SpecialFolder.ApplicationData`.

### Expected behavior

The returned folder should have the actual user directory as the root. So instead of combining with `GetFolderPathCore(SpecialFolder.Personal, SpecialFolderOption.None)` it should be combined with `GetFolderPathCore(SpecialFolder.UserProfile, SpecialFolderOption.None)`.

### Actual behavior

The wrong folder is used as the user's home directory.

It seems there is no specific macOS implementation of this code but that the code in `Environment.iOS.cs` is used.

### Configuration

Tested on .NET 8.0 on macOS Sonoma 14.4 on an Apple Silicon MacBook Pro.

**Comment by vcsjones** [comment]
> It seems there is no specific macOS implementation of this code but that the code in Environment.iOS.cs is used.

I can't reproduce this with a standard macOS application. Are you using a MAUI / Mac Catalyst application?

**Comment by MarcoMiltenburg** [comment]
Yes, the target platform is `net8.0-maccatalyst`.

**Comment by am11** [comment]
This seems to be by design macOS security feature.

Repro:
```c#
using static System.Environment.SpecialFolder;

Console.WriteLine($"{nameof(ApplicationData)}: {Environment.GetFolderPath(ApplicationData)}");
Console.WriteLine($"{nameof(Desktop)}: {Environment.GetFolderPath(Desktop)}");
Console.WriteLine($"{nameof(Favorites)}: {Environment.GetFolderPath(Favorites)}");
Console.WriteLine($"{nameof(Fonts)}: {Environment.GetFolderPath(Fonts)}");
Console.WriteLine($"{nameof(InternetCache)}: {Environment.GetFolderPath(InternetCache)}");
Console.WriteLine($"{nameof(MyDocuments)}: {Environment.GetFolderPath(MyDocuments)}");
Console.WriteLine($"{nameof(MyMusic)}: {Environment.GetFolderPath(MyMusic)}");
Console.WriteLine($"{nameof(MyPictures)}: {Environment.GetFolderPath(MyPictures)}");
Console.WriteLine($"{nameof(MyVideos)}: {Environment.GetFolderPath(MyVideos)}");
```

On osx-arm64 14.4.1, at first the values of Desktop and MyDocuments were empty:
```yaml
ApplicationData: /Users/am11/Library/Application Support
Desktop: 
Favorites: /Users/am11/Library/Favorites
Fonts: /Users/am11/Library/Fonts
InternetCache: /Users/am11/Library/Caches
MyDocuments: 
MyMusic: /Users/am11/Music
MyPictures: /Users/am11/Pictures
MyVideos: /Users/am11/Movies
```
Enabling Desktop and Documents in Privacy & Security for Terminal:
<img width="465" alt="image" src="https://github.com/dotnet/runtime/assets/3840695/4ec948df-38fa-47fd-9128-c8a8900f962c">
it outputs:
```yaml
ApplicationData: /Users/am11/Library/Application Support
Desktop: /Users/am11/Desktop
Favorites: /Users/am11/Library/Favorites
Fonts: /Users/am11/Library/Fonts
InternetCache: /Users/am11/Library/Caches
MyDocuments: /Users/am11/Documents
MyMusic: /Users/am11/Music
MyPictures: /Users/am11/Pictures
MyVideos: /Users/am11/Movies
```

**Comment by MarcoMiltenburg** [comment]
> This seems to be by design macOS security feature.

I don't think this is related. In your output at least the directories are correct. Only when a security feature is turned on they are empty which is fine.

In my case the returned directories are incorrect and non-existent.

**Comment by am11** [comment]
You are right, the values returned on macCatalyst and iOS are a bit strange:

```yaml
# net8.0-maccatalyst
ApplicationData: /Users/am11/Library/Containers/com.companyname.app1/Data/Documents/.config
Desktop: /Users/am11/Library/Containers/com.companyname.app1/Data/Documents/Desktop
Favorites: /Users/am11/Library/Containers/com.companyname.app1/Data/Library/Favorites
Fonts: /Users/am11/Library/Containers/com.companyname.app1/Data/Documents/.fonts
InternetCache: /Users/am11/Library/Containers/com.companyname.app1/Data/Library/Caches
MyDocuments: /Users/am11/Library/Containers/com.companyname.app1/Data/Documents
MyMusic: /Users/am11/Library/Containers/com.companyname.app1/Data/Documents/Music
MyPictures: /Users/am11/Library/Containers/com.companyname.app1/Data/Documents/Pictures
MyVideos: /Users/am11/Library/Containers/com.companyname.app1/Data/Documents/Videos

# net8.0-ios
ApplicationData: /Users/am11/Library/Developer/CoreSimulator/Devices/B4FD0CE9-ADEE-45C9-A97D-F74D28384BA8/data/Containers/Data/Application/7FF2BBC9-0749-4E51-92AC-3D6295C01EC6/Documents/.config
Desktop: /Users/am11/Library/Developer/CoreSimulator/Devices/B4FD0CE9-ADEE-45C9-A97D-F74D28384BA8/data/Containers/Data/Application/7FF2BBC9-0749-4E51-92AC-3D6295C01EC6/Documents/Desktop
Favorites: /Users/am11/Library/Developer/CoreSimulator/Devices/B4FD0CE9-ADEE-45C9-A97D-F74D28384BA8/data/Containers/Data/Application/7FF2BBC9-0749-4E51-92AC-3D6295C01EC6/Library/Favorites
Fonts: /Users/am11/Library/Developer/CoreSimulator/Devices/B4FD0CE9-ADEE-45C9-A97D-F74D28384BA8/data/Containers/Data/Application/7FF2BBC9-0749-4E51-92AC-3D6295C01EC6/Documents/.fonts
InternetCache: /Users/am11/Library/Developer/CoreSimulator/Devices/B4FD0CE9-ADEE-45C9-A97D-F74D28384BA8/data/Containers/Data/Application/7FF2BBC9-0749-4E51-92AC-3D6295C01EC6/Library/Caches
MyDocuments: /Users/am11/Library/Developer/CoreSimulator/Devices/B4FD0CE9-ADEE-45C9-A97D-F74D28384BA8/data/Containers/Data/Application/7FF2BBC9-0749-4E51-92AC-3D6295C01EC6/Documents
MyMusic: /Users/am11/Library/Developer/CoreSimulator/Devices/B4FD0CE9-ADEE-45C9-A97D-F74D28384BA8/data/Containers/Data/Application/7FF2BBC9-0749-4E51-92AC-3D6295C01EC6/Documents/Music
MyPictures: /Users/am11/Library/Developer/CoreSimulator/Devices/B4FD0CE9-ADEE-45C9-A97D-F74D28384BA8/data/Containers/Data/Application/7FF2BBC9-0749-4E51-92AC-3D6295C01EC6/Documents/Pictures
MyVideos: /Users/am11/Library/Developer/CoreSimulator/Devices/B4FD0CE9-ADEE-45C9-A97D-F74D28384BA8/data/Containers/Data/Application/7FF2BBC9-0749-4E51-92AC-3D6295C01EC6/Documents/Videos
```

@akoeplinger, is this by design (`Documents/Desktop` instead of `Desktop` etc.)?
