### ISSUE TITLE
Application Build with sdk .NET9 were not working in Azure app service(Linux)

### ISSUE THREAD

**Issue by tossnet** [dotnet/runtime#109867]
### Description

I have a simple Blazor Server app that I upgraded from .NET8 to .NET9. No problem (Debug/Release). When deploying to Azure App Service, I get the error page : 
**:( Application Error
If you are the application administrator, you can access the [diagnostic resources].**

I have no errror during my deployment. All lights are green

### Reproduction Steps

Here's my pipeline where I simply changed the SDK version from 8.0 to 9.0.100

```yaml
trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  displayName: 'Installing .NET Core SDK...'
  inputs:
    packageType: 'sdk'
    version: '9.0.100'

- script: dotnet build --configuration $(buildConfiguration) myproj/myproj.csproj
  displayName: 'dotnet build $(buildConfiguration)...'
- task: DotNetCoreCLI@2
  displayName: 'Publishing App...'
  inputs:
    command: publish
    publishWebProjects: false
    projects: 'myproj/myproj.csproj'
    arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: true

- task: PublishBuildArtifacts@1
  displayName: 'Publishing Build Artifacts...'
```

My agent job :   

```yaml
steps:
- task: AzureRmWebAppDeployment@4
  displayName: 'Azure App Service Deploy: MyProj'
  inputs:
    azureSubscription: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
    appType: webAppLinux
    WebAppName: SodeaSoftStore
    packageForLinux: '$(System.DefaultWorkingDirectory)/_Website /drop/MyProj.zip'
    RuntimeStack: 'DOTNETCORE|9.0'
    StartupCommand: 'dotnet MyProj.dll'
```

### Expected behavior

The application should work properly without any errors as it runs properly in Local and works perfectly with .NET 8 ( local and deployed)

### Actual behavior

only this error page : 
**:( Application Error
If you are the application administrator, you can access the [diagnostic resources].**
