### ISSUE TITLE
dotnet-sdk, version 9.0.101 fails with CMake 3.31.2 on Gentoo

### ISSUE THREAD

**Issue by xgqt** [dotnet/runtime#110664]
### Description

Bug discovered via Gentoo's unstable CI pipeline. See also: https://bugs.gentoo.org/946334

.NET SDK 9.0.101 fails to build with CMake. 

Error:

```
      -- Looking for pthread_create in c - not found
      CMake Error at /var/tmp/portage/dev-dotnet/dotnet-sdk-9.0.101/work/dotnet-sdk-9.0.101/src/runtime/src/native/l
ibs/configure.cmake:646 (check_library_exists):
        check_library_exists Macro invoked with incorrect arguments for macro
        named: CHECK_LIBRARY_EXISTS
      Call Stack (most recent call first):
        /var/tmp/portage/dev-dotnet/dotnet-sdk-9.0.101/work/dotnet-sdk-9.0.101/src/runtime/src/native/libs/CMakeLists.txt:112 (include)
      
...

      -- Performing Test HAVE_MKSTEMP - Failed
      CMake Error at /var/tmp/portage/dev-dotnet/dotnet-sdk-9.0.101/work/dotnet-sdk-9.0.101/src/runtime/src/native/libs/configure.cmake:771 (message):
        Cannot find mkstemps nor mkstemp on this platform.
      Call Stack (most recent call first):
        /var/tmp/portage/dev-dotnet/dotnet-sdk-9.0.101/work/dotnet-sdk-9.0.101/src/runtime/src/native/libs/CMakeLists.txt:112 (include)
```

Logs, compressed via XZ: https://bugs.gentoo.org/attachment.cgi?id=913885

### Reproduction Steps

use SDK 9.0.101, install cmake >=3.31.2, run prep & build, result: build fails to compile runtime

### Expected behavior

build passes with cmake 3.31.2

### Actual behavior

build fails

### Regression?

yes(?) in build system

### Known Workarounds

downgrade cmake, Gentoo stable is 3.30.6

### Configuration

see https://bugs.gentoo.org/946334 attachments

### Other information

> check_library_exists Macro invoked with incorrect arguments for macro

**Comment by janvorli** [comment]
@xgqt I was able to build it fine with cmake 3.31.2 on Ubuntu 22.04, so the problem rather seems to be specific to the Gentoo.
In fact, looking at the logs from gentoo, the build has failed due to the cmake config script not being able to find either mkstemps or mkstemp.
> Cannot find mkstemps nor mkstemp on this platform

It essentially means that the compilation of the following code has failed
```c
    #include <stdlib.h>
    #include <unistd.h>
    #include <string.h>

    int main(void)
    {
        return mkstemps(\"abc\", 3);
    }
```
or 
```c
    #include <stdlib.h>
    #include <unistd.h>
    #include <string.h>

    int main(void)
    {
        return mkstemp(\"abc\");
    }
```

I wonder if gentoo in the recent version has that in some other header file or something like that. Can you try to build those two using clang on that distro? That may give us more info on what's going on.

**Comment by xgqt** [comment]
> #include <stdlib.h>
>     #include <unistd.h>
>     #include <string.h>
> 
>     int main(void)
>     {
>         return mkstemp(\"abc\");
>     }

@janvorli both of those snippets fail because You escaped the "abc" string. 

Without a escape they compile ok on stable Gentoo with Clang version 19 (in C mode).

But in C++ mode with these warnings:

```
t1.cpp:7:21: warning: ISO C++11 does not allow conversion from string literal to 'char *' [-Wwritable-strings]
    7 |     return mkstemps("abc", 3);
      |                     ^
1 warning generated.
```

```
t2.cpp:7:20: warning: ISO C++11 does not allow conversion from string literal to 'char *' [-Wwritable-strings]
    7 |     return mkstemp("abc");
      |                    ^
1 warning generated.
```

**Comment by xgqt** [comment]
Is it possible to look into some log file (of CMake or .NET SDK) and see why either mkstemps or mkstemp is not found?

**Comment by xgqt** [comment]
In case of mkstemps we also had this report: https://bugs.gentoo.org/938485

**Comment by janvorli** [comment]
Ah, sorry for the escaped strings, I have not realized that they are escaped in the cmake scripts. But seeing that your compilation that succeeded generated warnings, it can be due to the fact that we have set the compiler to treat warnings as errors for the runtime build.
You can check cmake log files for the real reason. cmake generates `CMakeConfigureLog.yaml` file with info on all the configuration checks. There are actually several such files as the config scripts are used for various parts of the runtime. The one you'd want to look in is located at the following path (for Release build):
`artifacts/obj/native/net10.0-linux-Release-x64/CMakeFiles/CMakeConfigureLog.yaml`. In my case, the part of the HAVE_MKSTEMPS looks like this:
```
      - "Performing Test HAVE_MKSTEMPS"
    directories:
      source: "/home/janvorli/git/runtime3/artifacts/obj/native/net10.0-linux-Release-x64/CMakeFiles/CMakeScratch/TryCompile-gTa3nK"
      binary: "/home/janvorli/git/runtime3/artifacts/obj/native/net10.0-linux-Release-x64/CMakeFiles/CMakeScratch/TryCompile-gTa3nK"
    cmakeVariables:
      CMAKE_C_FLAGS: " -std=gnu99 -Wno-declaration-after-statement -D_GNU_SOURCE"
      CMAKE_C_FLAGS_RELEASE: "-O3 -DNDEBUG"
      CMAKE_EXE_LINKER_FLAGS: "-fuse-ld=lld -pie -Wl,--build-id=sha1 -Wl,-z,relro,-z,now"
      CMAKE_POSITION_INDEPENDENT_CODE: "ON"
    buildResult:
      variable: "HAVE_MKSTEMPS"
      cached: true
      stdout: |
        Change Dir: '/home/janvorli/git/runtime3/artifacts/obj/native/net10.0-linux-Release-x64/CMakeFiles/CMakeScratch/TryCompile-gTa3nK'

        Run Build Command(s): /usr/bin/cmake -E env VERBOSE=1 /usr/bin/gmake -f Makefile cmTC_55d58/fast
        /usr/bin/gmake  -f CMakeFiles/cmTC_55d58.dir/build.make CMakeFiles/cmTC_55d58.dir/build
        gmake[1]: Entering directory '/home/janvorli/git/runtime3/artifacts/obj/native/net10.0-linux-Release-x64/CMakeFiles/CMakeScratch/TryCompile-gTa3nK'
        Building C object CMakeFiles/cmTC_55d58.dir/src.c.o
        /usr/bin/clang-14 -DHAVE_MKSTEMPS  -std=gnu99 -Wno-declaration-after-statement -D_GNU_SOURCE  -Werror -Wno-error=unused-value -Wno-error=unused-variable -Wno-error=builtin-requires-header -Wunguarded-availability -O3 -DNDEBUG -std=gnu11 -fPIE -MD -MT CMakeFiles/cmTC_55d58.dir/src.c.o -MF CMakeFiles/cmTC_55d58.dir/src.c.o.d -o CMakeFiles/cmTC_55d58.dir/src.c.o -c /home/janvorli/git/runtime3/artifacts/obj/native/net10.0-linux-Release-x64/CMakeFiles/CMakeScratch/TryCompile-gTa3nK/src.c
        Linking C executable cmTC_55d58
        /usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_55d58.dir/link.txt --verbose=1
        /usr/bin/clang-14  -std=gnu99 -Wno-declaration-after-statement -D_GNU_SOURCE  -Werror -Wno-error=unused-value -Wno-error=unused-variable -Wno-error=builtin-requires-header -Wunguarded-availability -O3 -DNDEBUG -fuse-ld=lld -pie -Wl,--build-id=sha1 -Wl,-z,relro,-z,now  CMakeFiles/cmTC_55d58.dir/src.c.o -o cmTC_55d58  -lrt
        gmake[1]: Leaving directory '/home/janvorli/git/runtime3/artifacts/obj/native/net10.0-linux-Release-x64/CMakeFiles/CMakeScratch/TryCompile-gTa3nK'

      exitCode: 0
```

**Comment by xgqt** [comment]
> Ah, sorry for the escaped strings, I have not realized that they are escaped in the cmake scripts. But seeing that your compilation that succeeded generated warnings, it can be due to the fact that we have set the compiler to treat warnings as errors for the runtime build. You can check cmake log files for the real reason. cmake generates `CMakeConfigureLog.yaml` file with info on all the configuration checks. There are actually several such files as the config scripts are used for various parts of the runtime. The one you'd want to look in is located at the following path (for Release build): `artifacts/obj/native/net10.0-linux-Release-x64/CMakeFiles/CMakeConfigureLog.yaml`. In my case, the part of the HAVE_MKSTEMPS looks like this:

@janvorli 

Thanks, it might come handy when I will test this on my machine.
I see that both bugs that supposedly fail to find mkstemps use LTO in CXXLFAGS and LDFLAGS and I suppose this might be the issue.

It might take some time to re-run thsi on CI since I think the directory with `artifacts/obj/...` was not saved, sadly.

**Comment by xgqt** [comment]
See also: https://bugs.gentoo.org/946334#c10

**Comment by janvorli** [comment]
As for the bug you have linked, the error is caused by the fact that pthread_create was found neither in libpthread nor in libc. That means that PTHREAD_LIBRARY is not set and thus the `check_library_exists` gets wrong first argument.
```cmake
check_library_exists(${PTHREAD_LIBRARY} pthread_condattr_setclock "" HAVE_PTHREAD_CONDATTR_SETCLOCK)
```

**Comment by janvorli** [comment]
The reason may be that there are some command line options for linker / compiler that break the detection. Again, the `CMakeConfigureLog.yaml` would help to pinpoint the real problem. 
Btw, cmake older than 3.29 were putting the configuration info into CMakeOutput.log and CMakeError.log files instead.

**Comment by xgqt** [comment]
Reproduced with:
```
export CXXFLAGS="-O2 -pipe -march=native -fno-diagnostics-color -Werror=lto-type-mismatch -Werror=strict-aliasing -Werror=odr  -flto"
export LDFLAGS="-Wl,-O1 -Wl,--as-needed -Wl,-z,pack-relative-relocs -Wl,--defsym=__gentoo_check_ldflags__=0  -Werror=lto-type-mismatch  -Werror=strict-aliasing  -Werror=odr  -flto"
export CFLAGS="-O2 -pipe -march=native -fno-diagnostics-color -Werror=lto-type-mismatch -Werror=strict-aliasing -Werror=odr  -flto"
```

Those are the FLAGS that were set on the Gentoo Tinderbox CI.

And this is the failure:

```yaml
      - "Looking for pthread_create in pthread"
    directories:
      source: "/var/notmp/portage/dev-dotnet/dotnet-sdk-9.0.101/work/dotnet-sdk-9.0.101/src/runtime/artifacts/obj/coreclr/linux.x64.Release/CMakeFiles/CMakeScratch/TryCompile-Omh5Z4"
      binary: "/var/notmp/portage/dev-dotnet/dotnet-sdk-9.0.101/work/dotnet-sdk-9.0.101/src/runtime/artifacts/obj/coreclr/linux.x64.Release/CMakeFiles/CMakeScratch/TryCompile-Omh5Z4"
    cmakeVariables:
      CMAKE_CXX_COMPILER_CLANG_SCAN_DEPS: "/usr/lib/llvm/19/bin/clang-scan-deps"
      CMAKE_C_FLAGS: "-O2 -pipe -march=native -fno-diagnostics-color -Werror=lto-type-mismatch -Werror=strict-aliasing -Werror=odr -std=gnu99 -Wno-declaration-after-statement -D_GNU_SOURCE"
      CMAKE_C_FLAGS_RELEASE: "-O3 -DNDEBUG"
      CMAKE_EXE_LINKER_FLAGS: "-fuse-ld=lld -pie -Wl,--build-id=sha1 -Wl,-z,relro,-z,now"
      CMAKE_POSITION_INDEPENDENT_CODE: "ON"
    buildResult:
      variable: "HAVE_LIBPTHREAD"
      cached: true
      stdout: |
        Change Dir: '/var/notmp/portage/dev-dotnet/dotnet-sdk-9.0.101/work/dotnet-sdk-9.0.101/src/runtime/artifacts/obj/coreclr/linux.x64.Release/CMakeFiles/CMakeScratch/TryCompile-Omh5Z4'
        
        Run Build Command(s): /usr/bin/cmake -E env VERBOSE=1 /usr/bin/gmake -f Makefile cmTC_c5557/fast
        /usr/bin/gmake  -f CMakeFiles/cmTC_c5557.dir/build.make CMakeFiles/cmTC_c5557.dir/build
        gmake[1]: Entering directory '/var/notmp/portage/dev-dotnet/dotnet-sdk-9.0.101/work/dotnet-sdk-9.0.101/src/runtime/artifacts/obj/coreclr/linux.x64.Release/CMakeFiles/CMakeScratch/TryCompile-Omh5Z4'
        Building C object CMakeFiles/cmTC_c5557.dir/CheckFunctionExists.c.o
        /usr/lib/ccache/bin/clang-19   -O2 -pipe -march=native -fno-diagnostics-color -Werror=lto-type-mismatch -Werror=strict-aliasing -Werror=odr -std=gnu99 -Wno-declaration-after-statement -D_GNU_SOURCE -DCHECK_FUNCTION_EXISTS=pthread_create  -Werror -Wno-error=unused-value -Wno-error=unused-variable -Wno-error=builtin-requires-header -O3 -DNDEBUG -std=gnu11 -fPIE -MD -MT CMakeFiles/cmTC_c5557.dir/CheckFunctionExists.c.o -MF CMakeFiles/cmTC_c5557.dir/CheckFunctionExists.c.o.d -o CMakeFiles/cmTC_c5557.dir/CheckFunctionExists.c.o -c /var/notmp/portage/dev-dotnet/dotnet-sdk-9.0.101/work/dotnet-sdk-9.0.101/src/runtime/artifacts/obj/coreclr/linux.x64.Release/CMakeFiles/CMakeScratch/TryCompile-Omh5Z4/CheckFunctionExists.c
        error: unknown warning option '-Werror=lto-type-mismatch'; did you mean '-Werror=selector-type-mismatch'? [-Werror,-Wunknown-warning-option]
        gmake[1]: *** [CMakeFiles/cmTC_c5557.dir/build.make:82: CMakeFiles/cmTC_c5557.dir/CheckFunctionExists.c.o] Error 1
        gmake[1]: Leaving directory '/var/notmp/portage/dev-dotnet/dotnet-sdk-9.0.101/work/dotnet-sdk-9.0.101/src/runtime/artifacts/obj/coreclr/linux.x64.Release/CMakeFiles/CMakeScratch/TryCompile-Omh5Z4'
        gmake: *** [Makefile:133: cmTC_c5557/fast] Error 2
        
      exitCode: 2
```

So here the "unknown" option `-Werror=lto-type-mismatch` was treated with error.
