### ISSUE TITLE
dotnet core 3.1 self-contained snap

### ISSUE THREAD

**Issue by Soarc** [dotnet/runtime#1634]
I'm trying to create dotnet core console application for linux and distribute it via snapcraft.io platform. 
I've created simple console app via `dotnet new console` command and build it using `dotnet build -c release --self-contained -r linux-x64`. After that made snap package using following `snapcraft.yaml` config:

```
name: snap-test-console
version: 1.0.0
summary: Dotnet core snap test
description: |
  Testing dotnet core in strict confinment
base: core18
architectures:
- amd64
confinement: strict
grade: stable

parts:
  snap-test-console:
    plugin: dump
    source: bin/release/netcoreapp3.1/linux-x64/publish/
    stage-packages:
    - liblttng-ust0
    - libcurl4
    - libssl1.0.0
    - libkrb5-3
    - zlib1g
    - libicu60

apps:
  snap-test-console:
    command: snap-test-console
    plugs:
    - network
    - network-bind
    - removable-media
    - home

```

To build snap package i used `snapcraft` command.
After installing produced package with `snap install snap-test-console_*.snap --dangerous` command I run console app. But it failed with `Failed to create CoreCLR, HRESULT: 0x80070008` message. I've done some digging and find out from syslog following SECCOMP issue:

`] audit: type=1326 audit(1578771141.872:317): auid=1000 uid=1000 gid=1000 ses=2 pid=11025 comm="snap-test-conso" exe="/snap/snap-test-console/x1/snap-test-console" sig=0 arch=c000003e syscall=203 compat=0 ip=0x7f09cd37def7 code=0x50000`

I analyzed `syscall=203` :
```
$ scmp_sys_resolver 203
sched_setaffinity
```

So adding `process-control` interface to snap plugs fixes the issue. But this required manually connecting process-control interface after snap installation, which I want to avoid.

So my question is following: 
Is there any way to workaround or change this behavior, so dotnet core runtime did not call `sched_setaffinity` kernel function and didn't required process-control interface?

Here is [strace](https://gist.github.com/Soarc/fb3dfbd03d649b0827d64d857917972c) output in case you need it.

I'm using Ubuntu 18.04.2 LTS.
