### ISSUE TITLE
Builds failing with subset violation

### ISSUE THREAD

**Issue by jaredpar** [dotnet/runtime#1967]
Official builds are failing on a number of architectures with the following:

> /__w/1/s/eng/liveBuilds.targets(89,5): error : The CoreCLR artifacts path does not exist '/datadisks/disk1/workspace/_work/1/s/artifacts/transport/coreclr'. The CoreCLR subset category must be built before building this project. [/__w/1/s/src/libraries/System.Buffers/src/System.Buffers.csproj]

There have been similar bug reports in the past but there has never been a definitive repro. This has failed at least two builds in a row hence appears fairly definitive:

- https://dev.azure.com/dnceng/internal/_build/results?buildId=491110
- https://dev.azure.com/dnceng/internal/_build/results?buildId=491154

**Comment by dagood** [comment]
When the build unzips the build drop, it uses this path:

> `/usr/bin/tar -xvf /__w/1/s/__download__/CoreCLRProduct_Linux_x64_release/CoreCLRProduct_Linux_x64_release.tar.gz -C `**`/__w/1/s/artifacts/transport/coreclr`**

Then the build complains about `/datadisks/disk1/workspace/_work/1/s/artifacts/transport/coreclr`.

I think the mismatch is the problem. Looking at the YAML is good to start with, but agent changes could be to blame too (maybe we hard-coded a dependency on a certain root path that changed).

**Comment by jaredpar** [comment]
Looks like it's affecting builds other than official too

> https://dnceng.visualstudio.com/public/_build/results?buildId=491123

**Comment by jaredpar** [comment]
@safern can you take a look at this?

**Comment by ViktorHofer** [comment]
This could also be related to path changes on the helix agents. Unsure.

**Comment by jaredpar** [comment]
Here is the expanded YML file for this particular section

```yml
    - task: ExtractFiles@1
      displayName: Unzip CoreCLR build drop
      inputs:
        archiveFilePatterns: $(Build.SourcesDirectory)/__download__/$(_coreClrArtifactName)/$(_coreClrArtifactName)$(archiveExtension)
        destinationFolder: $(_coreClrDownloadPath)
        cleanDestinationFolder: true
```

Wonder if the agent is now giving back different values for `$(Build.SourcesDirectory)`
