### ISSUE TITLE
Test failure: Assertion failed '(budget >= 0) && (budget <= m_mapSelectBudget)'

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/runtime#55241]
System.Data.Common.Tests

win-x64

COMPlus_JitStress=2
COMPlus_JitStressRegs=2

(at least)

https://dev.azure.com/dnceng/public/_build/results?buildId=1219289&view=ms.vss-test-web.build-test-results-tab&runId=36354488&resultId=186161&paneView=dotnet-dnceng.dnceng-build-release-tasks.helix-test-information-tab

```
C:\h\w\AFFD097D\w\A6EA0937\e>set COMPlus 
COMPlus_JitStress=2
COMPlus_JitStressRegs=2
COMPlus_TieredCompilation=0

C:\h\w\AFFD097D\w\A6EA0937\e>call RunTests.cmd --runtime-path C:\h\w\AFFD097D\p 
----- start Sat 07/03/2021 10:09:29.21 ===============  To repro directly: ===================================================== 
pushd C:\h\w\AFFD097D\w\A6EA0937\e\
"C:\h\w\AFFD097D\p\dotnet.exe" exec --runtimeconfig System.Data.Common.Tests.runtimeconfig.json --depsfile System.Data.Common.Tests.deps.json xunit.console.dll System.Data.Common.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing 
popd
===========================================================================================================

C:\h\w\AFFD097D\w\A6EA0937\e>"C:\h\w\AFFD097D\p\dotnet.exe" exec --runtimeconfig System.Data.Common.Tests.runtimeconfig.json --depsfile System.Data.Common.Tests.deps.json xunit.console.dll System.Data.Common.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing  
  Discovering: System.Data.Common.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.Data.Common.Tests (found 1811 of 1813 test cases)
  Starting:    System.Data.Common.Tests (parallel test collections = on, max threads = 4)

Assert failure(PID 1756 [0x000006dc], Thread: 5968 [0x1750]): Assertion failed '(budget >= 0) && (budget <= m_mapSelectBudget)' in 'System.Data.Tests.Common.DataTableMappingCollectionTest:.ctor():this' during 'Do value numbering' (IL size 145)

    File: D:\workspace\_work\1\s\src\coreclr\jit\valuenum.cpp Line: 2221
    Image: C:\h\w\AFFD097D\p\dotnet.exe

----- end Sat 07/03/2021 10:09:50.40 ----- exit code -1073740286 ----------------------------------------------------------
```

@dotnet/jit-contrib

**Comment by briansull** [comment]
Triage: ValueNumbering

**Comment by BruceForstall** [comment]
Couldn't repro locally. Triggered another run to see if it still repros in the CI:

https://dev.azure.com/dnceng/public/_build/results?buildId=1243635&view=results

**Comment by BruceForstall** [comment]
I can repro on Windows x64 with:
```
set COMPlus_TieredCompilation=0
set COMPlus_JitStressModeNamesOnly=1
set COMPlus_JitStressModeNames= STRESS_BB_PROFILE STRESS_LEGACY_INLINE

c:\gh\runtime\artifacts\bin\System.Data.Common.Tests\net6.0-Release>c:\gh\runtime\artifacts\tests\coreclr\windows.x64.Checked\Tests\Core_Root\corerun.exe xunit.console.dll System.Data.Common.Tests.dll -parallel none -verbose -method "System.Data.Tests.Common.DataTableMappingCollectionTest.RemoveException1"
```

**Comment by BruceForstall** [comment]
JitDump before crash is 
```
N001 [000093]   LCL_VAR   V00 this         u:1 (last use) => $80 {InitVal($40)}
N002 [003270]   CNS_INT   8 field offset Fseq[_tableMapCollection] => $182 {LngCns:  8}
N003 [003271]   ADD       => $94d {ADD($80, $182)}
N005 [000100]   LCL_VAR   V12 tmp11        u:2 (last use) => $a78 {JitNew($895, $839)}
  VNApplySelectors:
    VNForHandle(_tableMapCollection) is $896, fieldType is ref
      AX2: $896 != $151 ==> select([$2a8]store($2a5, $151, $2a7), $896) ==> select($2a5, $896).
      AX2: $896 != $15c ==> select([$2a5]store($2a3, $15c, $2a4), $896) ==> select($2a3, $896).
      AX2: $896 != $144 ==> select([$2a3]store($a4c, $144, $2a2), $896) ==> select($a4c, $896).
      AX2: $896 != $151 ==> select([$2a0]store($29d, $151, $29f), $896) ==> select($29d, $896).
      AX2: $896 != $15c ==> select([$29d]store($29b, $15c, $29c), $896) ==> select($29b, $896).
      AX2: $896 != $144 ==> select([$29b]store($7b1, $144, $29a), $896) ==> select($7b1, $896).
      AX2: $896 != $151 ==> select([$299]store($296, $151, $298), $896) ==> select($296, $896).
      AX2: $896 != $15c ==> select([$296]store($294, $15c, $295), $896) ==> select($294, $896).
      AX2: $896 != $144 ==> select([$294]store($749, $144, $293), $896) ==> select($749, $896).
      AX2: $896 != $151 ==> select([$291]store($28e, $151, $290), $896) ==> select($28e, $896).
      AX2: $896 != $15c ==> select([$28e]store($28c, $15c, $28d), $896) ==> select($28c, $896).
      AX2: $896 != $144 ==> select([$28c]store($62e, $144, $28b), $896) ==> select($62e, $896).
      AX2: $896 != $151 ==> select([$28a]store($287, $151, $289), $896) ==> select($287, $896).
      AX2: $896 != $15c ==> select([$287]store($285, $15c, $286), $896) ==> select($285, $896).
      AX2: $896 != $144 ==> select([$285]store($53f, $144, $284), $896) ==> select($53f, $896).
      AX2: $896 != $141 ==> select([$282]store($81, $141, $281), $896) ==> select($81, $896).
      AX2: $896 != $141 ==> select([$282]store($81, $141, $281), $896) ==> select($81, $896).
      AX2: $896 != $141 ==> select([$282]store($81, $141, $281), $896) ==> select($81, $896).
      AX2: $896 != $141 ==> select([$282]store($81, $141, $281), $896) ==> select($81, $896).
      AX2: $896 != $151 ==> select([$291]store($28e, $151, $290), $896) ==> select($28e, $896).
      AX2: $896 != $15c ==> select([$28e]store($28c, $15c, $28d), $896) ==> select($28c, $896).
      AX2: $896 != $144 ==> select([$28c]store($62e, $144, $28b), $896) ==> select($62e, $896).
      AX2: $896 != $151 ==> select([$291]store($28e, $151, $290), $896) ==> select($28e, $896).
      AX2: $896 != $15c ==> select([$28e]store($28c, $15c, $28d), $896) ==> select($28c, $896).
      AX2: $896 != $144 ==> select([$28c]store($62e, $144, $28b), $896) ==> select($62e, $896).
      AX2: $896 != $151 ==> select([$291]store($28e, $151, $290), $896) ==> select($28e, $896).
      AX2: $896 != $15c ==> select([$28e]store($28c, $15c, $28d), $896) ==> select($28c, $896).
      AX2: $896 != $144 ==> select([$28c]store($62e, $144, $28b), $896) ==> select($62e, $896).
      AX2: $896 != $151 ==> select([$2a0]store($29d, $151, $29f), $896) ==> select($29d, $896).
      AX2: $896 != $15c ==> select([$29d]store($29b, $15c, $29c), $896) ==> select($29b, $896).
      AX2: $896 != $144 ==> select([$29b]store($7b1, $144, $29a), $896) ==> select($7b1, $896).
      AX2: $896 != $151 ==> select([$2a0]store($29d, $151, $29f), $896) ==> select($29d, $896).
      AX2: $896 != $15c ==> select([$29d]store($29b, $15c, $29c), $896) ==> select($29b, $896).
      AX2: $896 != $144 ==> select([$29b]store($7b1, $144, $29a), $896) ==> select($7b1, $896).
      AX2: $896 != $151 ==> select([$2a0]store($29d, $151, $29f), $896) ==> select($29d, $896).
      AX2: $896 != $15c ==> select([$29d]store($29b, $15c, $29c), $896) ==> select($29b, $896).
      AX2: $896 != $144 ==> select([$29b]store($7b1, $144, $29a), $896) ==> select($7b1, $896).
```
