### ISSUE TITLE
.NET 6 with specific Dynatrace versions does not start up in a AKS, and produces no logs

### ISSUE THREAD

**Issue by aullom1** [dotnet/runtime#64760]
### Description

I have a .NET 6 API that I would like to run in AKS.  Locally it works just fine.  In AKS the pod will start up, but the container produces no logs and refuses all connections.  I can exec into the container and run `dotnet MyApp.Api.dll` but the command will just hang and not write any output.

Exec'ing into the container and manually running `dotnet MyApp.Api.dll` will just hang and produce no output.

### Reproduction Steps

Generate a minimal .NET 6 webapi (.e.g `dotnet new webapi -minimal -o MyApp.Api`).

Create a Dockerfile and build and push to a repo.

```dockerfile
FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app

# Switch the default port from 80 to 5000
ENV ASPNETCORE_URLS=http://+:5000 \
    # Enable detection of running in a container
    DOTNET_RUNNING_IN_CONTAINER=true

EXPOSE 5000

# Create a group and user to run the ASP.NET Core application
RUN addgroup --system dotnetappgroup && \
	adduser --system --ingroup dotnetappgroup --shell /bin/sh dotnetappuser && \
	mkdir -p /local/ && \
	chown dotnetappuser:dotnetappgroup /local && \
	chown dotnetappuser:dotnetappgroup /app

# Update Docker to run all future commands as the appuser user.
USER dotnetappuser

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
ARG NuGetConfig=NuGet.Config
WORKDIR /src
COPY . .
RUN dotnet restore "MyApp.Api/MyApp.Api.csproj"
WORKDIR "/src/MyApp.Api"
RUN dotnet build "MyApp.Api.csproj" -c Release -o /app/build --no-restore

FROM build AS publish
RUN dotnet publish "MyApp.Api.csproj" -c Release -o /app/publish --no-restore

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "MyApp.Api.dll"]
```

Create an AKS cluster.  Obviously there can be a ton of variability here.  I am using:

|||
|--|--|
| Kubernetes version | 1.20.9 |
| Node image version | AKSUbuntu-1804gen2containerd-2021.10.19 |
| Container runtime version | containerd://1.4.9+azure |

Deploy your app.  The important bits about the manifest are:

```yaml
image: <YOUR_IMAGE_REFERENCE>
imagePullPolicy: Always
name: myapp
ports:
- containerPort: 5000
  protocol: TCP
resources:
  limits:
    cpu: 200m
    memory: 500Mi
  requests:
    cpu: 100m
    memory: 200Mi
```

### Expected behavior

The pod should start up, and the logs should show the typical startup output (e.g. Now listening on port...).

### Actual behavior

The pod reports that it is running, but there are no logs, and all connections are refused.

### Regression?

Prior versions of .NET Core do not have this problem.

**Comment by CaveSven** [comment]
We observe the exact same behaviour, even for a minimal console application printing nothing but "Hello World" to the console.

**Comment by aullom1** [comment]
> We observe the exact same behaviour, even for a minimal console application printing nothing but "Hello World" to the console.
> 
> Edit: this might be related: https://giters.com/Azure/azure-functions-dotnet-worker/issues/727

Interesting.  As of 12 days ago the image for function apps was fixed, but no other images have been fixed.

**Comment by mangod9** [comment]
We will try to repro this issue. Does this repro even if you configure with 1000+ millicores. Wonder if something under a 1000 is causing an issue.

**Comment by aullom1** [comment]
> We will try to repro this issue. Does this repro even if you configure with 1000+ millicores. Wonder if something under a 1000 is causing an issue.

I tried it again with req/limit of 1000/3000 with the same result.  I wasn't too hopeful since the nonprod env has no trouble with 100/300.

**Comment by mangod9** [comment]
I am not able to repro this on a single console app. Is it possible to capture a dump using dotnet-dump so we could investigate further? 

This is the config I tried:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: testalloc
  labels:
    app: k8stest
spec:
  replicas: 1
  template:
    metadata:
      name: k8stest
      labels:
        app: k8stest
    spec:
      containers:
      - name: k8stest
        image: <youracr>.azurecr.io/k8stest:v7
        resources:
          limits:
            cpu: 3000m
            memory: 7Gi
          requests:
            cpu: 1000m
            memory: 7Gi
        ports:
          - containerPort: 80
  selector:
    matchLabels:
      app: k8stest
```

We also have a sample app which has been ported over to use .NET 6: https://github.com/dotnet-architecture/eShopOnContainers
