### ISSUE TITLE
JsonNode.ToJsonString(JsonSerializerOptions options) Throw  OutOfMemoryException

### ISSUE THREAD

**Issue by saber-wang** [dotnet/runtime#67943]
### Description

Occasionally throw memory overflow when using JsonNode.ToJsonString

### Reproduction Steps

The size of a single JsonObject is within 30000000 bytes

var transObj = new JsonObject();
transObj .ToJsonString(new JsonSerializerOptions(JsonSerializerDefaults.Web)
                {
                    Encoder = System.Text.Encodings.Web.JavaScriptEncoder.UnsafeRelaxedJsonEscaping
                }))

### Expected behavior

Return string

### Actual behavior

 Throw  OutOfMemoryException

dumps: https://github.com/saber-wang/dumps

### Configuration

Run in container
base image: mcr.microsoft.com/dotnet/runtime:6.0-alpine

memory configuration
```
        resources:
          limits:
            memory: 2Gi
          requests:
            memory: 256Mi
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
          privileged: true
```
