### ISSUE TITLE
Question: how to bind a Dictionary in an Options class?

### ISSUE THREAD

**Issue by drauch** [dotnet/runtime#71736]
I have the following options class:
```
class MyOptions
{
    public Dictionary<string, MyOptionDetails> Prop { get; set; }
}
```
and the following appsettings.yml:
```
MyOptions:
  Prop:
    First:
      ValueA: "a1"
      ValueB: "b1"
    Second:
      ValueA: "a2"
      ValueB: "b2"
```

How to bind this Options class using a ConfigurationBinder? I think I will need to customize the binding logic somehow for the property, as Dictionary seems to be a non-standard construct for ASP.NET Core. How to register custom binding logic at the container?

Best regards,
D.R.
