### ISSUE TITLE
Support running perf benchmarks from `dotnet/performance` on a PR, and compare with a baseline

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#76533]
- We should have a way to run perf benchmarks (from `dotnet/performance`) on a `dotnet/runtime` PR
- This could be through a new pipeline, like`/azp run runtime-wasm-perf-compare`
- The corresponding yml can be used to configure parameters for this, like:

```yml
parameters:
- name: baseline
  type: object
  default:
    repoUrl: 'https://github.com/dotnet/runtime'
    branchOrCommit: 'main'
    name: ''

- name: candidate
  type: object
  default:
    repoUrl: 'https://github.com/dotnet/runtime'
    branchOrCommit: 'main' #FIXME: should default to PR head somehow
    name: ''

- name: filter
  type: string
  default: ''
```

- The `candidate` should default to the PR branch HEAD
- The `baseline` can point to any branch, or commit on `dotnet/runtime`, or a fork
- It should generate jobs that would:
1. Build+run-perf for each of the relevant refs (eg. baseline, candidate), and upload the results. And this should support using filters to restrict the benchmarks to run.
2. A separate job to collect the results from (1), and generate a report based on the results. This could use the existing `dotnet/performance`'s `ResultsComparer` tool.

Results from (1) for `baseline` can then be downloaded so subsequent runs can skip the build+perf step for `baseline`.

cc @lewing @steveisok @DrewScoggins @adamsitnik @akoeplinger
