### ISSUE TITLE
Simple .NET 7 Api is using more than 1.5Gigs of memory for Apple Mac Mini Arm 64 processor 

### ISSUE THREAD

**Issue by chhandakdey** [dotnet/runtime#86703]
### Description

We created a simple Api (simple-check) using .NET default template which has weather forecast api by default. I have used .NET 7 to create the Api.

![image](https://github.com/dotnet/runtime/assets/12728691/b573ec24-0c1d-4211-b4cf-517582776677)

I have used the below dockerfile -

```
FROM mcr.microsoft.com/dotnet/aspnet:7.0-alpine AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:7.0-alpine AS build
WORKDIR /src
COPY ["simple-check/simple-check.csproj", "simple-check/"]
RUN dotnet restore "simple-check/simple-check.csproj"
COPY . .
WORKDIR "/src/simple-check"
RUN dotnet build "simple-check.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "simple-check.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "simple-check.dll"]
```
I have used the below compose file -

```
version: '3.9'

services:
  simple-check:
    image: simple-check
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "40898:80"
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
```

When I run it in my development system which is Macbook pro -

![image](https://github.com/dotnet/runtime/assets/12728691/97906ce6-e98f-491b-89bf-7a14ad559c6e)

Its only occupying 18MiB - please check the last line

![image](https://github.com/dotnet/runtime/assets/12728691/f35cda8c-716f-45d3-96ac-5a92efccc00d)

However, the same docker image if I run it in Mac Mini, its taking more than 1.5 G

![image](https://github.com/dotnet/runtime/assets/12728691/93f6f384-af88-4600-8e0a-b8ce760a7177)

Please check the first one -

![image](https://github.com/dotnet/runtime/assets/12728691/8efaa0e2-c6ec-4135-b45a-0d193b63eefe)

I have tried with multi platform image also, but the result is same; So, wanted to know how to reduce the default memory usage? However, I can use docker resource limits to limit the resource and same is running fine with 200MB memory, but wanted to understand the reason behind the default memory usage.

### Reproduction Steps

1. Create a simple .NET 7 Api - like Weather Forecast.
2. Add docker support.
3. Run the application in Amd 64 machine using docker desktop.
4. you notice the default memory usage is very low around 18 Mb.
5. Run the same application (you can create multi platform image, but it does not differ the result) in Mac Mini (Arm 64 V8) using docker desktop.
6. you notice the default memory usage is around 1.8Gb.

### Expected behavior

The default memory usage should be same across amd 64 and arm 64 processors.

### Actual behavior

amd 64 is taking very less memory compared to arm 64.
