### ISSUE TITLE
mac m1 using System.Data.Odbc on .net 7 (core) 

### ISSUE THREAD

**Issue by amirjalali1** [dotnet/runtime#88007]
### Description

I'm trying to connect to an ODBC database using System.Data.Odbc
I'm facing the following issue

```
Fatal error. System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.
```
I'm already using docker with virtualization enabled and in docker composed i have add:

```
    environment:
      - DOCKER_DEFAULT_PLATFORM=linux/amd64
    platform: linux/amd64
    build:
      context: .
      dockerfile: myproject/Dockerfile
```

so whenever i'm doing the following :

```
      OdbcConnectionStringBuilder odbcConnectionStringBuilder =
        new OdbcConnectionStringBuilder()
        {
            Dsn = "Simba Spark ODBC DSN"
        }
        
```
        
I get error

### Reproduction Steps

 create a .net 7 application on mac with docker

install System.Data.Odbc via nuget

set docker to use x64

```
      OdbcConnectionStringBuilder odbcConnectionStringBuilder =
        new OdbcConnectionStringBuilder()
        {
            Dsn = "Simba Spark ODBC DSN"
        }
        
```

### Expected behavior

connect to ODBC connection

### Actual behavior

getting exception
