### ISSUE TITLE
Why DOTNET_GCHeapHardLimitPercent not working?

### ISSUE THREAD

**Issue by careless6666** [dotnet/runtime#92113]
Hi. We have dotnet application with  <TargetFramework>net7.0</TargetFramework>
and k8s limits
```
resources:
  limits:
    cpu: "4"
    memory: "3Gi"
  requests:
    cpu: "1.5"
    memory: "2Gi"
```

and dotnet variables
```
env:
  - name: ASPNETCORE_ENVIRONMENT
    value: "Production"
  - name: DOTNET_gcServer
    value: "1"
  - name: DOTNET_gcConcurrent
    value: "1"
  - name: DOTNET_GCConserveMemory
    value: "5"
  - name: DOTNET_GCRetainVM
    value: "0"
  - name: DOTNET_GCHeapHardLimitPercent
    value: "0x28"
```

My metrics from gc
<img width="1663" alt="Screenshot 2023-09-15 at 1 23 28 PM" src="https://github.com/dotnet/runtime/assets/8223175/bbdaafaa-fe0a-4251-ba0e-00c9c570b535">
dotnet_totalmemory
<img width="1648" alt="Screenshot 2023-09-15 at 1 23 49 PM" src="https://github.com/dotnet/runtime/assets/8223175/f359664d-76d3-4b74-ae16-2e86a170473b">
dotnet_collection_count_total

And metrics from os
<img width="1653" alt="Screenshot 2023-09-15 at 1 24 23 PM" src="https://github.com/dotnet/runtime/assets/8223175/ecd19dd0-c789-48bb-9d31-6758475ce6d9">
I set up DOTNET_GCRetainVM and expected see same memory allocation for dotnet and for os memory. 
So going beyond the limits of memory usage would be ok if it were short-term, but here it is clearly not going to go to the set 40%
We research this question, because we receive oom kill, on some applications, and there is no memory leak in these applications. If you call GC.Collect() memoey will be cleaned

I expect the memory to stay at 1.2 GB (40%)

**Comment by janvorli** [comment]
@careless6666 the `DOTNET_GCHeapHardLimitPercent` should be a hexadecimal value, but without the `0x` prefix. All DOTNET_xxx numeric values work this way.

**Comment by careless6666** [comment]
I changed values to this

```
env:
  - name: ASPNETCORE_ENVIRONMENT
    value: "Production"
  - name: DOTNET_gcServer
    value: "1"
  - name: DOTNET_gcConcurrent
    value: "1"
  - name: DOTNET_GCConserveMemory
    value: "5"
  - name: DOTNET_GCRetainVM
    value: "0"
  - name: DOTNET_GCHeapHardLimitPercent
    value: "28"
```
but result not changed
<img width="1659" alt="Screenshot 2023-09-20 at 9 58 40 PM" src="https://github.com/dotnet/runtime/assets/8223175/57e3aa16-b73b-4803-a96e-ffaccd8ea9e5">
