### ISSUE TITLE
FileVersionInfo.ProductMajorPart, FileVersionInfo.ProductMinorPart, FileVersionInfo.ProductBuildPart are not set in NET8

### ISSUE THREAD

**Issue by quicoli** [dotnet/runtime#95919]
Hi!

I migrated my WPF application from NET6 to NET8 and noticed a different behavior in the FileVersionInfo.
After some investigation I see that the dotnet publish is working differently in NET8.

I have self-hosted build server with NET 8 SDK installed and latest Visual Studio installed.
My pipeline publishes my desktop app using the following task:

```
      - task: DotNetCoreCLI@2
        displayName: "Build application"
        inputs:
          command: build
          projects: '**/MyApp.Shell.csproj' 
          arguments: '--runtime win-x64 --configuration $(buildConfiguration) --self-contained -p:Version=$(versionMajorMinorPatch).$(versionRevision);InformationalVersion=$(versionMajorMinorPatch).(versionRevision)+$(shortHash)'
```

```
      - task: DotNetCoreCLI@2
        displayName: "Publish self-contained application"
        inputs:
          command: publish
          publishWebProjects: false
          projects: '**/MyApp.Shell.csproj' 
          arguments: '--runtime win-x64 --self-contained --configuration $(buildConfiguration) --output $(Pipeline.Workspace)/publish -p:Version=$(versionMajorMinorPatch).$(versionRevision) -p:InformationalVersion=$(versionMajorMinorPatch).$(versionRevision)+$(shortHash) -p:PublishReadyToRun=true'
          zipAfterPublish: false
```

When my application starts I have this code:

``` csharp
        var assembly = Assembly.GetExecutingAssembly();
        logger.Debug(assembly.Location);

        var fileVersion = FileVersionInfo.GetVersionInfo(assembly.Location);

        logger.Debug($"{fileVersion.ProductMajorPart}.{fileVersion.ProductMinorPart}.{fileVersion.ProductBuildPart}");
        logger.Debug($"{fileVersion.FileMajorPart}.{fileVersion.FileMinorPart}.{fileVersion.FileBuildPart}");
```

Checking the log file I can see that  individual **Product* calls return 0 while File* calls return the correct version**. However the `ProductVersion` property has the correct value.

Under NET6 I can get the correct version using `FileVersionInfo.ProjectMajorPart`.

I cant' say where is the problem exactly.

My workaround is to use FileMajorPart, FileMinorPart and FileBuildPart now. 

Publishing the WPF application through Visual Studio is fine. It returns the correct value.

Could you please have a look on this?
